### ISSUE TITLE
Sprint-1: Progress Overview

### ISSUE THREAD

**Issue by catherine9** [webdev6/obscure-book-genres#18]
**Progress on each task.**

After completing the tasks of finding our audience, personas & competitors , we were able to figure out our website goals and work on the skeleton of the web app. We completed a sitemap,wireframe and designed our logo. We are now in the progress of figuring out the visual design of our web app and creating our interactive prototype for our upcoming sprint.

@thomasjbradley

**Comment by Paulinamissio** [comment]
**How did you & the sprint succeed? What was positive?**
As a group we were able to meet our sprint goals on time. I myself was able to get the personas done quickly and start working on the sitemap to get it done in time for the next meeting. 

**How did you & the sprint fail? What was negative?**
The sprint was hard to figure out at first so things got checked off last minute. The only negative was figuring out our sitemap.

**Comment by fakeha-abdullah** [comment]
**How did you & the sprint succeed? What was positive?**
As the project manager I worked on our apps target audience and goals and then moved on doing research on possible competitors. As well as, sitemap and wireframes.

**How did you & the sprint fail? What was negative?**
Contribution to the sitemap and figuring out our wireframes was a bit of a struggle at first especially when we assigned it for our first sprint, however we managed to pull it off as a team.

**Comment by catherine9** [comment]
**How did you & the sprint succeed? What was positive?**
As a group I was able to help create a sitemap to narrow down what the main tasks for the web app. I was also able to build a small mood-board to get a better visual for our goal. 
**How did you & the sprint fail? What was negative?**
Creating a sprint was tricky to get around and It ended up being done last minute. Our topic is about books so for a bit the sitemap was a challenge to wrap our heads as to how it will be done

**Comment by thomasjbradley** [comment]
👍
