### ISSUE TITLE
Usability Testing 

### ISSUE THREAD

**Issue by fakeha-abdullah** [webdev6/obscure-book-genres#26]
**Task 1 - View Genres**
- User one - Good and pretty straight forward.
- User two - Simple!
- User three - Easy to find.
**Task 2 - Select Genre**
- User one - pretty straight forward with the use of cards.
- User two - selected the genre pretty quick!
- User three - Was easy to find.
**Task 3 - Read Book**
- User one - Button was found easily. Once on reading page (Making the genre bold and tweak the visual design of the page a little)
- User two - Simple and clear! But maybe having the reviews before the user starts reading the book.
- User three - Pretty clear and easy to use.
**Task 4 - Add the book to your favourites**
- User one - Found icon real quick and it made sense.
- User two - The use of icon was easy.
- User three - Clicked on the icon and it was recognisable. 
**Task 5 - View your bookmarks**
- User one - Found icon real quick but suggested having the page number somewhere within the layout or having it appear when user clicks on the bookmark icon to indicate what page they just bookmarked.
- User two - The use of icon was easy and understandable.
- User three - Was a little confused between the difference between favourites and bookmarks but understood it once clicking and viewing the page.

**Overall:** 
The usability testing went smooth and the users found the web app pretty simple and straightforward. Our main focus when creating this app was to keep it very user friendly because many book apps that were competitors had issues mainly based on accessibility and visual design. Minor frictions appeared with making things a little bit more clearer in certain pages and are going to get solved easily in our upcoming sprint.
@thomasjbradley

**Comment by thomasjbradley** [comment]
👍
