### ISSUE TITLE
UX rubric

### ISSUE THREAD

**Issue by catherine9** [webdev6/obscure-book-genres#3]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Good teamwork** | Never there | Doesn't participate | Some participation, | Good participation | Excellent participation |
| **Ability to fill many roles** | Didn't start | Barely started | Made small effort | Made some effort |Decent amount of work | Filled all the roles |
| **Well produced wireframe** | Nothing done | Barely started | Decent indentation, just a couple missing pieces | Fair amount of work | | Well indented, fully valid, good semantics |
| **Easy to use** | Nope | Not as easy to use | Little complicated | Fairly easy to use | Very easy to use |
| **Personality and design** | Bleh | Not a lot of personality | some personality in the design | Nicely done but needs a bit more | | Very well designed |
| **Good sprint planning and execution** | Didn't start | Barely started | Little bit of planning but ready to execute | Fair amount of planning and execution | | Very well done on planning and execution |

**Comment by fakeha-abdullah** [comment]
_Graded rubric :_ 
**-Good teamwork -** 3
**-Ability to fill in many roles -**  2
**-Well produced wireframes-** 3
**-Easy to use -** 3
**-Personality and design-** 3
**Good sprint planning and execution-** 3
Overall : 17/18 (A+)
